version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: alina7/foodgram_backend:latest
    command: gunicorn --bind 0.0.0.0:8080 foodgram_backend.wsgi
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/app/media
    depends_on:
      - db


  frontend:
    container_name: foodgram-front
    image: alina7/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static/
      - media:/app/media
    depends_on:
      - backend
      - frontend
      - db
