# Generated by Django 4.2.14 on 2024-08-29 18:42

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Имя пользователя содержит недопустимые символы.'), users.validators.validate_username]),
        ),
    ]
